### ISSUE TITLE
Stupid question time

### ISSUE THREAD

**Issue by G7OEA** [urlgrey/hsmm-pi#57]
![mesh node-3](https://cloud.githubusercontent.com/assets/8453299/8989325/5841cd60-36e3-11e5-8ac6-15e4ae4b479a.PNG)
Hi Scott,
I have installed hsmm-pi on three P-pi2's. They can  all see each other on the network list. I have a couple of stupid questions.
How do I manage the nodes via the network. Do I have to connect to each on via the Ethernet port and then connect to the wen interface or can I connect to one node then remotely administer the others?
The second question is how the services work.
What I am trying to set up is a network that can ne set up in an emergency response centre. There will be some nodes configured as specialist providers such as an internet gateway and the router will provide the firewall, another a viop server. Some will be simple repeaters to filling the dark spaces in a building. The others will be the interface between the lan and the mesh.
I want to be able that a pc on say node 2 can ping and see the c$ chare on a pc on node 3 and so on. The plan was that the node2 would have the ip 172.27.2.10 and would give out a dhcp scope 11-19. Node 3 and ip of 172.27.2.20 and have a dhcp soap of 21 - 29 do you get the idea. When I do this I can’t ping.
I assume I am doing something stupendously stupid and fully accept the title of N00B. On the surface this build id simple to build onto the R-pi. The headwear is the right cost. you’re not tied to specific hardware. in the UK Linksys WRG54's are hard to come by and the ubiquity kit even harder.
Help, Please? There is a group of UK Hams wanting to use your software and were all as stuck as each other.

**Comment by argilo** [comment]
> Do I have to connect to each on via the Ethernet port and then connect to the wen interface or can I connect to one node then remotely administer the others?

You can connect to one and remotely administer the others via the web interface.

> I want to be able that a pc on say node 2 can ping and see the c$ chare on a pc on node 3 and so on.

At the moment, HSMM-Pi operates in NAT mode, which means that by default any machine connected to the Ethernet interface of the Pi can only make outbound connections. To receive incoming connections from the rest of the mesh, you need to configure port forwarding in the "Services" settings page.

Eventually I'd like to add a "direct" mode so that port forwarding is unnecessary: https://github.com/urlgrey/hsmm-pi/issues/79
