### ISSUE TITLE
Problems installing on Raspbian-Jessie

### ISSUE THREAD

**Issue by SDreher71** [urlgrey/hsmm-pi#58]
After install, localhost:8080 returns the Apache verification page. After editing /etc/apache/ports.conf to point the 8080 virtual host to /var/www, it returns a page with several of the hsmm-pi menu items, but with no css formatting. Clicking on any of the menu items on that page (status, login, etc) results in a 404 error.

**Comment by argilo** [comment]
Thanks for reporting this. I've added support for Jessie in https://github.com/urlgrey/hsmm-pi/pull/60.

The issue was that Jessie configures Apache a bit differently. Configuration files are stored in `/etc/apache2/conf-available` instead of `/etc/apache2/conf.d`, and web content is stored in `/var/www/html` instead of `/var/www`.

hsmm-pi should still work fine on Wheezy as well.

**Comment by SDreher71** [comment]
Nice work. Thanks!

**Comment by argilo** [comment]
By the way, you can use the new "Lite" version of Raspbian Jessie which omits lots of packages that hsmm-pi doesn't need.
