### ISSUE TITLE
Lite distribution has no X so can't do UI!

### ISSUE THREAD

**Issue by cbegg50** [urlgrey/hsmm-pi#81]
Your suggestion of Raspbian Jesse Lite does not have the X that the Admin interface uses.  I've had to refresh the SD card with Standard Jesse to use the script.  I'd already used a NOOBS installation on a Pi Zero, but for the second Pi node I thought I'd follow your instructions.  Bad idea1
Thanks for an otherwise superb product.  My brother G7AOR is also trying one and he is having problems with DHCP crashing the image.

Sorry, found it on my Laptop!  Please ignore this issue
73 de Colin, G4MCF

**Comment by argilo** [comment]
@cbegg50 Did you use the full Raspbian Jessie for your first install? Did everything work well? If so, I can add that as an option to the instructions for people who want to use the GUI.

**Comment by mathisono** [comment]
I don't use the light image unless I specifically need a head less node. I
run an aprs server so I need the ui.

73 kj6dzb
On Apr 20, 2016 4:43 AM, "Clayton Smith" <notifications@github.com> wrote:

Reopened #81 <https://github.com/urlgrey/hsmm-pi/issues/81>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/urlgrey/hsmm-pi/issues/81#event-634409271>
